#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <string.h>
#include "Match.h"


#define WIDTHCODE 4
#define LENGHTPLAYERNAME 20
typedef enum { false, true } bool;

int main ()
{
  
  void WriteRules();
  
  srand(time(NULL));

  
  struct Match *newMatch =Match__create();
  
  printf("#################################### MASTERMIND ####################################\n\n");

  WriteRules();
  
  printf("Insert your nickname. Max 20 characters, spaces included. \n\n");
  
  
  char playerName[LENGHTPLAYERNAME];
  scanf("%19s",playerName);
  printf("\n\n");
  printf("\n\n");

  Match__setPlayerName(newMatch,playerName);

  
  int codIsOk;

  
  bool exitCodeIsPressed = false;
  char inputExitCode;
  bool inputCodeIsValid = false; 
  
  int j;
  

  do
  {
    while(codIsOk == 0 && Match__attempts(newMatch) > 0 )
    {
      Match__increaseUsedAttempts(newMatch);

      char strTemp[WIDTHCODE];
      do
      {
        
        printf("\n");
        printf("Guess the number (four digit). You still have %d attempt/s \n\n",(Match__attempts(newMatch)));
        
        while((getchar())!='\n'); 
        
        scanf("%4s",strTemp);
        
        inputCodeIsValid = true;

        if(strTemp[0] == '0')
          inputCodeIsValid = false;
        else
        {
          int counterDigit = 0;
          for(j = 0; j < strlen(strTemp); j++)
          {
            if(!isdigit(strTemp[j]))
            {
              inputCodeIsValid = false;
              break;
            }
            else{
              counterDigit = counterDigit + 1;
            }
          }
          if(counterDigit != WIDTHCODE)
              inputCodeIsValid = false;
        }

        
      } while (inputCodeIsValid == false);
      
      
      inputCodeIsValid = false;
      int inputNumber = atoi(strTemp);
      int arrToCompare[WIDTHCODE];
      int size = SplitIntToArrayInt(arrToCompare, inputNumber);
      codIsOk= Match__findMatches(newMatch,(int)arrToCompare);
      
      if(codIsOk == 1){
        printf("\n\n");
        printf("Congratulations %s, You've guessed secret number in %d attempts.",Match__playerName(newMatch),(Match__usedAttempts(newMatch)));
      }
      else{
        printf("\n\n");
        printf("++ Valid digits in correct position %d",Match__numbersAtTheRightPlace(newMatch));
        printf("\n\n");
        printf("++ Valid digits in wrong position %d",Match__numbersAtTheWrongPlace(newMatch));
        printf("\n\n");
        printf("\n\n");
        Match__decreaseAttempts(newMatch);
      }
    }

    
    printf("\n\n Press [n]ew to begin a new match,  other input will close the player session.");
    scanf(" %1c", &inputExitCode); 
      
    if(inputExitCode != 'n')
      exitCodeIsPressed = true;
    else
    {
      printf("\n\n");
      printf("\n\n");
      Match__init(newMatch);
      codIsOk = false;
    }

  } while (exitCodeIsPressed == false);
  
  Match__destroy(newMatch);
  
  return 0;
}

void WriteRules()
{
  printf("+++++++++++++++++++++ Rules +++++++++++++++++++++++++++++++");
  printf("\n\n");
    printf("The purpose is guess a secret number, dynamically generated by PC.");
    printf("\n\n");
    printf("You'll have 9 attempts. On monitor, for each attempt you'll see: ");
    printf("\n\n");
    printf("1) Valid digits in correct position.");
    printf("\n\n");
    printf("2) Valid digits in wrong position.");
    printf("\n\n");
    printf("Pay attention:");
    printf("\n\n");
    printf("<--> Less of 4 numbers will be discarded, on input.");
    printf("\n\n");

  printf("\n\n");
  printf("+++++++++++++++++++++ Rules +++++++++++++++++++++++++++++++");
  printf("\n\n");
}






